---

- apt_key:
    state: present
    url: https://pkg.jenkins.io/debian/jenkins-ci.org.key

- apt_repository:
    filename: jenkins
    repo: 'deb http://pkg.jenkins.io/debian-stable binary/'
    state: present
    update_cache: yes

- apt:
    autoremove: yes
    cache_valid_time: 3600
    name: jenkins
    state: latest
    update_cache: yes

...
